#!/bin/bash

# --- Configuration for an Awesome Terminal Experience ---

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# --- Utility Functions ---

# Function to display a step message
step_message() {
    echo -e "\n${BLUE}>>> STEP $1: ${YELLOW}$2${NC}"
}

# Function to check for required commands
check_command() {
    local cmd=$1
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "${RED}ERROR: The command '$cmd' is not found. Please install it and try again.${NC}"
        exit 1
    fi
}

# --- Pre-flight Checks ---

step_message 1 "Checking system dependencies (Docker, Docker Compose, and OpenSSL for secret generation)"
check_command docker
check_command openssl

# Check for both docker-compose legacy and the modern 'docker compose' plugin
if command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
    echo -e "${GREEN}✓ Found legacy 'docker-compose' command.${NC}"
elif docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
    echo -e "${GREEN}✓ Found modern 'docker compose' plugin.${NC}"
else
    echo -e "${RED}ERROR: Neither 'docker-compose' nor 'docker compose' plugin was found. Please install Docker Compose.${NC}"
    exit 1
fi

# --- Interactive Configuration ---

step_message 2 "Gathering project details and host port mappings"

# 1. Project Name
read -r -p "Enter a name for your project (e.g., netgoat-stack): " PROJECT_NAME
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME="netgoat_stack"
    echo -e "${YELLOW}Using default project name: ${PROJECT_NAME}${NC}"
fi

# 2. Host Port for Frontend (web browser access)
read -r -p "Enter the external port for the Frontend (default: 8080): " FRONTEND_HOST_PORT
if ! [[ "$FRONTEND_HOST_PORT" =~ ^[0-9]+$ ]]; then
    FRONTEND_HOST_PORT=8080
fi
echo -e "${GREEN}Frontend accessible on host port: ${FRONTEND_HOST_PORT}${NC}"

# 3. Host Port for Backend API
read -r -p "Enter the external port for the Backend API (default: 3001): " BACKEND_HOST_PORT
if ! [[ "$BACKEND_HOST_PORT" =~ ^[0-9]+$ ]]; then
    BACKEND_HOST_PORT=3001
fi
echo -e "${GREEN}Backend accessible on host port: ${BACKEND_HOST_PORT}${NC}"

# 4. Host Port for Central Mon Server
read -r -p "Enter the external port for Central Mon Server (default: 1933): " CENTRALMON_HOST_PORT
if ! [[ "$CENTRALMON_HOST_PORT" =~ ^[0-9]+$ ]]; then
    CENTRALMON_HOST_PORT=1933
fi
echo -e "${GREEN}CentralMon accessible on host port: ${CENTRALMON_HOST_PORT}${NC}"

# 5. Host Port for Log DB API
read -r -p "Enter the external port for Log DB API (default: 3010): " LOGDB_HOST_PORT
if ! [[ "$LOGDB_HOST_PORT" =~ ^[0-9]+$ ]]; then
    LOGDB_HOST_PORT=3010
fi
echo -e "${GREEN}LogDB accessible on host port: ${LOGDB_HOST_PORT}${NC}"

# 6. Host Port for MongoDB (optional external access)
read -r -p "Enter the external port for MongoDB (default: 27017): " MONGO_HOST_PORT
if ! [[ "$MONGO_HOST_PORT" =~ ^[0-9]+$ ]]; then
    MONGO_HOST_PORT=27017
fi
echo -e "${GREEN}MongoDB accessible on host port: ${MONGO_HOST_PORT}${NC}"

# 7. Host Port for MinIO (optional external access)
read -r -p "Enter the external port for MinIO (default: 9000): " MINIO_HOST_PORT
if ! [[ "$MINIO_HOST_PORT" =~ ^[0-9]+$ ]]; then
    MINIO_HOST_PORT=9000
fi
echo -e "${GREEN}MinIO accessible on host port: ${MINIO_HOST_PORT}${NC}"


# --- Internal Network Constants ---
BACKEND_PORT_INTERNAL=3001
CENTRALMON_PORT_INTERNAL=1933
LOGDB_PORT_INTERNAL=3010
FRONTEND_PORT_INTERNAL=80
BRACKETDNS_PORT_INTERNAL_DNS=53
MONGO_PORT_INTERNAL=27017
REDIS_PORT_INTERNAL=6379
MINIO_PORT_INTERNAL=9000

# --- File Generation ---

step_message 3 "Generating configuration files and cryptographic secrets"

# Generate strong, random secrets
MONGO_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')
MINIO_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')
REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')

# Generate JWT secrets (32 bytes = 64 hex chars)
NEW_SHARED_JWT_SECRET=$(openssl rand -hex 32)
NEW_DYNAMIC_SECRET_KEY_JWT_SECRET=$(openssl rand -hex 32)
NEW_JWT_SECRET=$(openssl rand -hex 32)

# For client-specific JWTs (CENTRAL_JWT_BACKEND, CENTRAL_JWT_LOGDB), these should be generated
# by CentralMonServer using the SHARED_JWT_SECRET. Since we can't run the server in Bash,
# we generate strong, base64-encoded placeholders derived from the secret for initial use.
CENTRAL_JWT_BACKEND_PLACEHOLDER=$(echo -n "Main_instance" | openssl dgst -sha256 -hmac "$NEW_SHARED_JWT_SECRET" | awk '{print $2}' | cut -c 1-64 | base64)
CENTRAL_JWT_LOGDB_PLACEHOLDER=$(echo -n "LogDB" | openssl dgst -sha256 -hmac "$NEW_SHARED_JWT_SECRET" | awk '{print $2}' | cut -c 1-64 | base64)

# 3a. Generate .env file
echo -e "${BLUE}Creating '.env' file for environment variables...${NC}"

cat << EOF > .env
# ====================================================================
# Environment Variables for $PROJECT_NAME Stack (Local/Development)
# Generated by setup-docker.sh on $(date)
# ====================================================================

# --- Core Settings ---
PROJECT_NAME=$PROJECT_NAME
DOCKER_REGISTRY=netgoat

# --- Host Port Mappings (User Defined) ---
FRONTEND_HOST_PORT=$FRONTEND_HOST_PORT
BACKEND_HOST_PORT=$BACKEND_HOST_PORT
CENTRALMON_HOST_PORT=$CENTRALMON_HOST_PORT
LOGDB_HOST_PORT=$LOGDB_HOST_PORT
MONGO_HOST_PORT=$MONGO_HOST_PORT
MINIO_HOST_PORT=$MINIO_HOST_PORT

# --- Internal Docker Ports (Fixed by application config) ---
BACKEND_PORT_INTERNAL=$BACKEND_PORT_INTERNAL
CENTRALMON_PORT_INTERNAL=$CENTRALMON_PORT_INTERNAL
LOGDB_PORT_INTERNAL=$LOGDB_PORT_INTERNAL
FRONTEND_PORT_INTERNAL=$FRONTEND_PORT_INTERNAL
BRACKETDNS_PORT_INTERNAL_DNS=$BRACKETDNS_PORT_INTERNAL_DNS
MONGO_PORT_INTERNAL=$MONGO_PORT_INTERNAL
REDIS_PORT_INTERNAL=$REDIS_PORT_INTERNAL
MINIO_PORT_INTERNAL=$MINIO_PORT_INTERNAL

# --- Internal Service URLs (using service names for Docker DNS) ---
CENTRAL_SERVER_URL=http://centralmon:\${CENTRALMON_PORT_INTERNAL}
NEXT_PUBLIC_BACKENDAPI=http://backend:\${BACKEND_PORT_INTERNAL}
NEXT_PUBLIC_LOGDB=http://logdb:\${LOGDB_PORT_INTERNAL}
MINIO_ENDPOINT=http://minio:\${MINIO_PORT_INTERNAL}

# NOTE: Frontend uses a public URL for external communication:
NEXT_PUBLIC_CENTRALMONSERVER=https://central.netgoat.xyz

# --- Local Database/Storage Dependencies (Internal URLs) ---
# All services now use the locally running MongoDB and Redis containers.
# Default MongoDB URI for Netgoat DB
MONGODB_URI_REMOTE=mongodb://netgoat_user:\${MONGO_ROOT_PASSWORD}@mongo:\${MONGO_PORT_INTERNAL}/Netgoat?authSource=admin
# MongoDB URI for CentralMon DB
MONGODB_URI_CENTRALMON=mongodb://netgoat_user:\${MONGO_ROOT_PASSWORD}@mongo:\${MONGO_PORT_INTERNAL}/CentralMon?authSource=admin
# Redis URL
REDIS_URL=redis://:\${REDIS_PASSWORD}@redis:\${REDIS_PORT_INTERNAL}

# Backend's Mongo reference
mongodb=\${MONGODB_URI_REMOTE}
# BracketDNS's Mongo reference
MONGO_URI=\${MONGODB_URI_REMOTE}


# --- Auto-Generated Secret Keys & Credentials ---
# MongoDB Secrets
MONGO_ROOT_USER=netgoat_user
MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD

# Redis Secret
REDIS_PASSWORD=$REDIS_PASSWORD

# MinIO Secrets
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=$MINIO_ROOT_PASSWORD

# JWT Secrets (Used by CentralMonServer)
SHARED_JWT_SECRET=$NEW_SHARED_JWT_SECRET
DYNAMIC_SECRET_KEY_JWT_SECRET=$NEW_DYNAMIC_SECRET_KEY_JWT_SECRET
JWT_SECRET=$NEW_JWT_SECRET # Used by Frontend

# Client-Specific JWTs (Strongly derived placeholders)
CENTRAL_JWT_BACKEND=$CENTRAL_JWT_BACKEND_PLACEHOLDER
CENTRAL_JWT_LOGDB=$CENTRAL_JWT_LOGDB_PLACEHOLDER

# --- Admin Credentials (Used by CentralMonServer) ---
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin

# --- Regional Settings ---
REGION_ID=MM
REGION_CONTINENT=asia
REGION_COUNTRY=MM
REGION_CITY=Yangon
ZONE_AUTH=quack
HOST_DOMAIN=netgoat.xyz
SERVICE_NAME_BRACKETDNS=ammy

# --- Debug Flag ---
DEBUG=true
EOF
echo -e "${GREEN}✓ Generated .env file with auto-generated secrets and local service URLs.${NC}"

# 3b. Generate Docker Compose File (docker-compose.yml)
echo -e "${BLUE}Generating 'docker-compose.yml' file with new local services...${NC}"

cat << EOF > docker-compose.yml
# ====================================================================
# Docker Compose Configuration for \${PROJECT_NAME} Stack
# Includes locally defined MongoDB, Redis, and MinIO services.
# ====================================================================
version: '3.8'

# --- Application Services ---
services:
  # ----------------------------------------------------
  # 1. Central Monitor Server (Authentication & Control)
  # ----------------------------------------------------
  centralmon:
    image: \${DOCKER_REGISTRY}/centralmon
    container_name: \${PROJECT_NAME}_centralmon
    restart: always
    env_file:
      - .env
    environment:
      # Use locally defined services via environment variables in .env
      PORT: \${CENTRALMON_PORT_INTERNAL}
      MONGODB_URI: \${MONGODB_URI_CENTRALMON}
    depends_on:
      - mongo
    ports:
      - "\${CENTRALMON_HOST_PORT}:\${CENTRALMON_PORT_INTERNAL}"
    networks:
      - \${PROJECT_NAME}_network

  # ----------------------------------------------------
  # 2. Backend API Service
  # ----------------------------------------------------
  backend:
    image: \${DOCKER_REGISTRY}/netgoat
    container_name: \${PROJECT_NAME}_backend
    restart: always
    env_file:
      - .env
    environment:
      BACKEND_PORT: \${BACKEND_PORT_INTERNAL}
      Central_server: \${CENTRAL_SERVER_URL}
      REDIS_URL: \${REDIS_URL}
      mongodb: \${mongodb}
    depends_on:
      - centralmon
      - logdb
      - mongo
      - redis
      - minio
    ports:
      - "\${BACKEND_HOST_PORT}:\${BACKEND_PORT_INTERNAL}"
    networks:
      - \${PROJECT_NAME}_network

  # ----------------------------------------------------
  # 3. Log Database API Service
  # ----------------------------------------------------
  logdb:
    image: \${DOCKER_REGISTRY}/logdb
    container_name: \${PROJECT_NAME}_logdb
    restart: always
    env_file:
      - .env
    environment:
      PORT: \${LOGDB_PORT_INTERNAL}
      Central_server: \${CENTRAL_SERVER_URL}
      Central_JWT: \${CENTRAL_JWT_LOGDB}
    depends_on:
      - centralmon
      - mongo
    ports:
      - "\${LOGDB_HOST_PORT}:\${LOGDB_PORT_INTERNAL}"
    networks:
      - \${PROJECT_NAME}_network

  # ----------------------------------------------------
  # 4. Frontend Web Interface (Next.js/React)
  # ----------------------------------------------------
  frontend:
    image: \${DOCKER_REGISTRY}/frontend
    container_name: \${PROJECT_NAME}_frontend
    restart: always
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_BACKENDAPI: \${NEXT_PUBLIC_BACKENDAPI}
      NEXT_PUBLIC_LOGDB: \${NEXT_PUBLIC_LOGDB}
      MONGODB_URI: \${MONGODB_URI_REMOTE}
    depends_on:
      - backend
    ports:
      - "\${FRONTEND_HOST_PORT}:\${FRONTEND_PORT_INTERNAL}"
    networks:
      - \${PROJECT_NAME}_network

  # ----------------------------------------------------
  # 5. Bracket DNS Service (DNS Resolution)
  # ----------------------------------------------------
  bracketdns:
    image: \${DOCKER_REGISTRY}/bracketdns
    container_name: \${PROJECT_NAME}_bracketdns
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URI: \${MONGO_URI}
      Central_server: \${CENTRAL_SERVER_URL}
      service: \${SERVICE_NAME_BRACKETDNS}
    depends_on:
      - centralmon
      - mongo
    # Bind to UDP port 53 for external DNS resolution (requires root/sudo)
    ports:
      - "53:\${BRACKETDNS_PORT_INTERNAL_DNS}/udp"
    networks:
      - \${PROJECT_NAME}_network

  # ----------------------------------------------------
  # --- Local Data Services ---
  # ----------------------------------------------------

  # 6. MongoDB
  mongo:
    image: mongo:6
    container_name: \${PROJECT_NAME}_mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: \${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: \${MONGO_ROOT_PASSWORD}
    volumes:
      - \${PROJECT_NAME}_mongo_data:/data/db
    ports:
      - "\${MONGO_HOST_PORT}:\${MONGO_PORT_INTERNAL}"
    networks:
      - \${PROJECT_NAME}_network

  # 7. Redis
  redis:
    image: redis:7-alpine
    container_name: \${PROJECT_NAME}_redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass \${REDIS_PASSWORD}
    volumes:
      - \${PROJECT_NAME}_redis_data:/data
    networks:
      - \${PROJECT_NAME}_network

  # 8. MinIO (S3-compatible Object Storage)
  minio:
    image: minio/minio
    container_name: \${PROJECT_NAME}_minio
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: \${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: \${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - \${PROJECT_NAME}_minio_data:/data
    ports:
      - "\${MINIO_HOST_PORT}:\${MINIO_PORT_INTERNAL}" # API port
      - "9001:9001" # Console/UI port
    networks:
      - \${PROJECT_NAME}_network


# --- Volume Definitions (for persistent data) ---
volumes:
  \${PROJECT_NAME}_mongo_data:
    driver: local
  \${PROJECT_NAME}_redis_data:
    driver: local
  \${PROJECT_NAME}_minio_data:
    driver: local

# --- Network Definition ---
networks:
  \${PROJECT_NAME}_network:
    driver: bridge
    name: \${PROJECT_NAME}_network

# Set project name for easier management and cleaner container names
name: \${PROJECT_NAME}

EOF
echo -e "${GREEN}✓ Generated docker-compose.yml file with 8 services.${NC}"


# --- Final Instructions ---

step_message 4 "Setup Complete! Your Awesome Multi-Service Stack is Ready."

echo -e "${GREEN}=====================================================${NC}"
echo -e "${GREEN}To start your services, run:${NC}"
echo -e "${YELLOW}  $COMPOSE_CMD --env-file .env up -d${NC}"
echo -e "${GREEN}=====================================================${NC}"
echo -e "${GREEN}Access the Frontend service at: http://localhost:$FRONTEND_HOST_PORT${NC}"
echo -e "${GREEN}Access the MinIO Console at:    http://localhost:9001 (Use credentials in the .env file)${NC}"
echo -e "${GREEN}To stop and remove containers, run: ${YELLOW}$COMPOSE_CMD --env-file .env down${NC}"
echo -e "\n${YELLOW}NOTE: Running the DNS service (bracketdns) on port 53/UDP often requires administrator privileges (sudo).${NC}"

# Make the script executable for future use (if it wasn't already run with 'bash')
chmod +x setup-docker.sh

exit 0